SELECT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    ON CC.CAR_ID = CH.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
GROUP BY CC.CAR_ID
ORDER BY CC.CAR_ID DESC;